# Generated by Django 3.2.7 on 2021-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificados', '0002_auto_20211113_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=None, max_length=200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
