# Generated by Django 3.2.7 on 2021-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificados', '0003_auto_20211113_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
