# Generated by Django 3.2.7 on 2021-11-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificados', '0008_alter_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
