# Generated by Django 3.2.7 on 2021-11-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificados', '0009_subcategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitem',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
